# Generated by Django 4.2.3 on 2023-07-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "members_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trakit.pair"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suser",
            fields=[
                ("suserid", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=11)),
                ("inHuddle", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("dueDate", models.DateField(verbose_name="Due date")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")]
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trakit.project"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pair",
            name="member1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pm1",
                to="trakit.suser",
            ),
        ),
        migrations.AddField(
            model_name="pair",
            name="member2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pm2",
                to="trakit.suser",
            ),
        ),
    ]
