# Generated by Django 4.2.3 on 2023-08-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trakit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="Nuevo", max_length=100),
            preserve_default=False,
        ),
    ]
