# Generated by Django 4.2.3 on 2023-08-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trakit", "0004_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="suser",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
